### PR TITLE
Cross build sbt

### LINKED ISSUE #4: cross build for sbt 1.x
Ho can I cross build for sbt 0.13.16 and 1.0.4?

### PR DESCRIPTION
**Pull request by yvoderatskyi**
Closes #4 

In this PR I added support to cross-build the plugin and additionally some minor refactorings of the `build.sbt` file.

### CODE REVIEW

**Comment by jtescher** [comment]
Looks good, thanks

**Comment by yvoderatskyi** [comment]
Thank you! Still for some reason I could not see set 1.x version of the plugin in Bintray. Do you publish it by hand or from Travis?

**Comment by jtescher** [comment]
By hand. Are there docs on publishing for multiple sbt versions?

**Comment by yvoderatskyi** [comment]
@jtescher sorry for the long delay. Some documentation can be found [here](https://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt-cross-building). Normally `^ publish` should be enough to publish both versions. For this particular case, sinse `0.13` version was published you might need to open REPL, switch sbt version to `1.x` and publish the artifact.

Kind regards,
Yurii

**Pull request merged**
